// ApplyFriend.java
package com.shanyangcode.userservice.model.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import lombok.experimental.Accessors;

import java.time.LocalDateTime;

/**
 * Friend request entity
 *
 * Responsibilities:
 * - Records the friend requests between users
 * - Tracks the request status (unread, accepted, rejected, read, expired)
 * - Supports the expiry mechanism
 */
@Data
@TableName("apply_friend")
@Accessors(chain = true)
public class ApplyFriend {

    /** Friend request id (primary key, generated by the distributed id generator). */
    @TableId(value = "apply_friend_id", type = IdType.ASSIGN_ID)
    private Long applyFriendId;

    /** Sender's user id (whoever made the request). */
    @TableField("sender_id")
    private Long senderId;

    /** Receiver's user id (whoever received the request). */
    @TableField("receiver_id")
    private Long receiverId;

    /** Message attached to the request; defaults to "Requesting to add you as a friend". */
    @TableField("message")
    private String message;

    /**
     * Request status
     * 0: unread (UNREAD)
     * 1: accepted (ACCEPTED)
     * 2: rejected (REJECTED)
     * 3: read (READ)
     * 4: expired (EXPIRED)
     */
    @TableField("status")
    private Integer status;

    @TableField("created_time")
    private LocalDateTime createdTime;

    @TableField("updated_time")
    private LocalDateTime updatedTime;
}