spring:
  application:
    name: RealTimeService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:49152/InfiniteChat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD}
  data:
    redis:
      database: 2
      host: 127.0.0.1
      port: 59000
      password: ${REDIS_PASSWORD}
      timeout: 30000
server:
  port: 8102