-- =============================================================================
-- InfiniteChat database schema
-- =============================================================================
-- Database name: InfiniteChat
-- Requires MySQL 8.0+ (uses the utf8mb4_0900_ai_ci collation, which MySQL 5.7 does not support)
-- Local development: the MySQL container is mapped to host port 49152; see README.md in the project root
--
-- How to run it:
--   mysql -h 127.0.0.1 -P 49152 -u root -p < sql/schema.sql
--
-- [WARNING] The first statement is DROP DATABASE IF EXISTS InfiniteChat, which deletes every
--           row in the database along with it. Run this only when initialising a fresh environment.
--
-- Conventions:
--   * Every primary key is a BIGINT generated by the application's snowflake algorithm
--     (SnowflakeUtil in the Common module / MyBatis-Plus IdType.ASSIGN_ID);
--     no table uses AUTO_INCREMENT, so the application sets the id explicitly on insert.
--   * Every monetary field is stored in cents as a BIGINT, to avoid floating-point precision problems.
--   * Timestamps are always created_time / updated_time, maintained by MySQL, with
--     updated_time carrying ON UPDATE CURRENT_TIMESTAMP.
--   * Deletion is always a logical flag on is_delete / status; rows are never physically removed.
--
-- Tables:
--   user                 users
--   session              conversations (one-to-one / group)
--   user_session         user-to-conversation membership
--   message              messages
--   friend               friendships
--   apply_friend         friend requests
-- =============================================================================


-- Drop the database if it already exists
DROP DATABASE IF EXISTS InfiniteChat;


-- Create the new database
CREATE DATABASE InfiniteChat;


-- Switch to the InfiniteChat database
USE InfiniteChat;


-- Users
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`
(
    `user_id`      BIGINT       NOT NULL COMMENT 'User ID',
    `phone`        CHAR(11)              DEFAULT NULL COMMENT 'Phone number',
    `email`        VARCHAR(128) NOT NULL COMMENT 'Email address',
    `password`     VARCHAR(256) NOT NULL COMMENT 'Password',
    `nickname`     VARCHAR(128) NOT NULL COMMENT 'Nickname',
    `avatar`       VARCHAR(512)          DEFAULT NULL COMMENT 'Avatar url',
    `gender`       TINYINT(1)   NOT NULL DEFAULT 2 COMMENT 'Gender: 0 female, 1 male, 2 unknown',
    `description`  TEXT                  DEFAULT NULL COMMENT 'Bio',
    `state`        TINYINT(1)   NOT NULL DEFAULT 0 COMMENT 'Status: 0 active, 1 banned, 2 deactivated',
    `role`         TINYINT(1)   NOT NULL DEFAULT 0 COMMENT 'Role: 0 regular user, 1 admin, 2 super admin',
    `created_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
    `updated_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update time',
    `is_delete`    TINYINT      NOT NULL DEFAULT 0 COMMENT 'Soft-delete flag (0 not deleted, 1 deleted)',
    PRIMARY KEY (`user_id`),
    UNIQUE KEY `idx_phone` (`phone`),
    UNIQUE KEY `idx_email` (`email`),
    KEY `idx_state` (`state`),
    KEY `idx_role` (`role`),
    KEY `idx_create_time` (`created_time`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci COMMENT = 'Users'
  ROW_FORMAT = Dynamic;


-- Conversations
DROP TABLE IF EXISTS `session`;
CREATE TABLE `session`
(
    `session_id`   BIGINT       NOT NULL COMMENT 'Conversation ID',
    `name`         VARCHAR(255)     DEFAULT NULL COMMENT 'Name',
    `avatar`       VARCHAR(255)     DEFAULT NULL COMMENT 'Conversation avatar',
    `type`         TINYINT      NOT NULL COMMENT 'Kind: 0 one-to-one, 1 group, 2 AI',
    `status`       TINYINT      NOT NULL COMMENT 'Status: 0 active, 1 deleted',
    `created_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
    `updated_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update time',
    PRIMARY KEY (`session_id`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci COMMENT = 'Conversations'
  ROW_FORMAT = Dynamic;


-- User-to-conversation membership
DROP TABLE IF EXISTS `user_session`;
CREATE TABLE `user_session`
(
    `user_id`      BIGINT   NOT NULL COMMENT 'User id',
    `session_id`   BIGINT   NOT NULL COMMENT 'Conversation id',
    `role`         TINYINT  NOT NULL COMMENT 'Role: 0 owner, 1 admin, 2 regular member',
    `status`       TINYINT  NOT NULL COMMENT 'Status: 0 active, 1 deleted',
    `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
    `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update time',
    PRIMARY KEY (`user_id`, `session_id`),
    INDEX `idx_session_id` (`session_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci COMMENT = 'User-to-conversation membership'
  ROW_FORMAT = Dynamic;


-- Messages
DROP TABLE IF EXISTS `message`;
CREATE TABLE `message`
(
    `message_id`   BIGINT   NOT NULL COMMENT 'Message id',
    `sender_id`    BIGINT   NOT NULL COMMENT 'Sender id',
    `session_id`   BIGINT   NOT NULL COMMENT 'Conversation id',
    `type`         TINYINT  NOT NULL COMMENT 'Message type: 0 text, 1 image, 3 red packet, 4 sticker',
    `content`      text     NOT NULL COMMENT 'Message content',
    `reply_id`     BIGINT            DEFAULT NULL COMMENT 'Referenced message id',
    `session_type` TINYINT  NOT NULL COMMENT 'Conversation type: 0 one-to-one, 1 group',
    `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
    `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update time',
    PRIMARY KEY (`message_id`) USING BTREE,
    INDEX `idx_session_time` (`session_id`, `created_time`),
    INDEX `idx_sender_time` (`sender_id`, `created_time`),
    INDEX `idx_reply_id` (`reply_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci COMMENT = 'Messages'
  ROW_FORMAT = Dynamic;


-- Friendships
DROP TABLE IF EXISTS `friend`;
CREATE TABLE `friend`
(
    `user_id`      BIGINT   NOT NULL COMMENT 'User ID',
    `friend_id`    BIGINT   NOT NULL COMMENT 'Friend ID',
    `status`       TINYINT  NOT NULL DEFAULT 0 COMMENT 'Friendship status: 0 friend, 1 blocked, 2 deleted',
    `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
    `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update time',
    PRIMARY KEY (`user_id`, `friend_id`),
    INDEX `idx_friend_id` (`friend_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci COMMENT = 'Friendships'
  ROW_FORMAT = Dynamic;


-- Friend requests
DROP TABLE IF EXISTS `apply_friend`;
CREATE TABLE `apply_friend` (
                                `apply_friend_id` bigint NOT NULL COMMENT 'Request ID',
                                `sender_id` bigint NOT NULL COMMENT 'Sender user ID',
                                `receiver_id` bigint NOT NULL COMMENT 'Receiver user ID',
                                `message` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'Requesting to add you as a friend' COMMENT 'Request message',
                                `status` tinyint NOT NULL DEFAULT '0' COMMENT 'Request status: 0 unread, 1 accepted, 2 rejected, 3 read, 4 expired',
                                `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation time',
                                `updated_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update time',
                                PRIMARY KEY (`apply_friend_id`),
                                UNIQUE KEY `uk_sender_receiver` (`sender_id`,`receiver_id`),
                                KEY `idx_sender_status` (`sender_id`,`status`),
                                KEY `idx_receiver_status` (`receiver_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='Friend requests';
